### ISSUE TITLE
Game freeze when using bottle bugs

### ISSUE THREAD

**Issue by Tsarchasm1** [ZoeyZolotova/mm-rando#157] opened 2022-01-25 02:06 UTC
Game freezes when placing a bottle bug into soft soil after a bean plant has been planted but not watered. Tested in the soil where the bean salesman is under the Deku Palace. Screen goes white and looks like the game tries to load the inverted song of time slow down screen as the clocks that appear under links feet are faintly visible.

**Comment by ZoeyZolotova** [comment] 2022-01-25 02:40
Hi, thanks for reporting the issue. I'm unable to reproduce the issue using the information provided. Can you please post your spoiler log for the seed? Would also be helpful in the future if you report issues via the bug-reports channel on discord.

**Comment by Tsarchasm1** [comment] 2022-01-26 00:09
Sorry, i deleted the seed and started a vanilla one. Wasn't aware you would ask for it. Good news is i ran into the same bug in the swamp skulltula house. There is definitely something going on with the bottle bugs, although it took me a while to replicate it, even on a vanilla seed. It had the same picture i described earlier but when i alt-tabbed the screen it changed to the one i put in the attachment. Also i cant find the discord anywhere. Every link i find is outdated, including in the about section of the program.
![Untitled](https://user-images.githubusercontent.com/22357271/151080572-d205767f-8dec-4e1a-9ea6-ad9262e4631f.png)

**Comment by Tsarchasm1** [comment] 2022-01-26 00:30
Edit: got it twice on the same hole in a row just now. 

![Untitled](https://user-images.githubusercontent.com/22357271/151082563-fc7eb6f9-77d7-4f4e-a5d5-98b32bbc3628.png)

**Comment by ZoeyZolotova** [comment] 2022-07-22 06:18
This has been fixed in the latest release. Thanks for the report.

**Closed by ZoeyZolotova** 2022-07-22 06:18 UTC
